FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir streamlit pandas plotly s3fs python-dotenv

EXPOSE 8501

CMD ["streamlit", "run", "dashboard_netflix.py", "--server.address=0.0.0.0"]
