services:
  minio:
    image: minio/minio:latest
    container_name: minio-aula03
    command: server /data --console-address ":9001"
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9011
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - minio_network
    restart: unless-stopped

  # MinIO Client (mc) para configuração inicial
  minio-client:
    image: minio/mc:latest
    container_name: minio-client-aula03
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 minioadmin minioadmin;
      mc mb myminio/raw-data --ignore-existing;
      mc mb myminio/bronze --ignore-existing;
      mc mb myminio/silver --ignore-existing;
      mc mb myminio/gold --ignore-existing;
      mc mb myminio/staging --ignore-existing;
      mc mb myminio/archive --ignore-existing;
      mc mb myminio/ml-models --ignore-existing;
      mc mb myminio/logs --ignore-existing;
      echo 'Buckets criados com sucesso (Aula 03 - Arquitetura Medallion)!';
      exit 0;
      "
    networks:
      - minio_network

volumes:
  minio_data:
    driver: local

networks:
  minio_network:
    driver: bridge
